#!/bin/sh

set -e

# The following keys (commented out lines) have been rotated
# and no longer work.  To make the `trainctl` script work, please
# get your own credentials and set these environment variables.
#
# export AWS_ACCESS_KEY=AKIAJF746WG4HR6IGEXQ
# export AWS_SECRET_KEY=AoXiWV+lCagS7xM9/svK8XfmmIGR26Napum86xAe
if [ -z "$AWS_ACCESS_KEY" ]
then
  echo "Please export AWS_ACCESS_KEY environment variable."
  exit 1
fi
if [ -z "$AWS_SECRET_KEY" ]
then
  echo "Please export AWS_SECRET_KEY environment variable."
  exit 1
fi

REGION=${REGION:-us-west-2}
case $REGION in
sa-east-1)
  AMI=ami-e99717f4
  ;;
eu-central-1)
  #AMI=ami-a4e1d8b9
  AMI=ami-accff2b1
  ;;
eu-west-1)
  #AMI=ami-9bdda0ec
  AMI=ami-47a23a30
  ;;
us-west-2)
  #AMI=ami-916e57a1
  #AMI=ami-f0091d91
  AMI=ami-5189a661
  ;;
us-east-1)
  AMI=ami-eb6b8480
  ;;
esac
export EC2_URL=https://ec2.$REGION.amazonaws.com/

case "$1" in
shell)
  export PS1="trainctl@$REGION# "
  exec $SHELL
  ;;
opensg)
  ec2-authorize -P tcp -p -1 default
  ec2-authorize -P udp -p -1 default
  ec2-authorize -P icmp -t -1:-1 default
  ;;
start)
  if [ -z "$2" ]
  then
    echo "Indicate number of instances to start."
    exit 1
  fi
  TOKEN=$(date +%Y-%m-%d-%H-%M-$USER)
  sed -i s/##SWARM_ID##/$SWARM_ID/g cloudinit.sh
  ec2-run-instances \
    --user-data-file cloudinit.sh \
    --instance-count $2 \
    --instance-type t2.small \
    --client-token $TOKEN \
    $AMI | grep ^RESERVATION
  IDS=$(ec2-describe-instances --filter client-token=$TOKEN | grep ^INSTANCE | awk '{print $2}')
  ec2-create-tags --tag Name=$TOKEN $IDS
  for ID in $IDS
  do
    while ! ec2-describe-instances $ID | grep ^NICASSOCIATION
    do
      sleep 3
    done
  done
  echo "Successfully created $2 instances with tag:"
  echo "$TOKEN"
  ;;
ips)
  if [ -z "$2" ]
  then
    echo "Please specify tag."
    exit 1
  fi
  ec2-describe-instances --filter tag:Name=$2 | grep ^NICASSOCIATION | awk '{print $2}'
  ;;
list)
  ec2-describe-instances | grep ^TAG
  ;;
stop)
  if [ -z "$2" ]
  then
    echo "Please specify tag."
    exit 1
  fi
  ec2-describe-instances --filter tag:Name=$2 | grep ^INSTANCE | awk '{print $2}' | xargs ec2-terminate-instances
  ;;
*)
  echo "$0 <start|stop|ips|list|opensg|shell> [n-instances|token...]"
  ;;
esac
