# DB // Cache
cache:
  image: redis

# Backend
back:
  image: maven:3.3.3-jdk-8
  command: mvn clean spring-boot:run
  volumes:
    - ~/.m2:/root/.m2
    - ./back/:/usr/src/app
  working_dir: /usr/src/app
  links:
    - cache:redis

# Frontend
front:
  build: front/
  ports:
    - "80:3000"
  volumes:
    - ./front/static/:/usr/src/app/static/
  links:
    - back:api
